name: website src dir

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: public/
          dest: result.zip
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: result.zip
          
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: my-artifact
          asset_content_type: application/gzip
