name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: public/
          dest: result.zip
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: result.zip
